### ISSUE TITLE
Streamline results uploading process

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#148]
One idea from @SAuroux: link directly to correct competition id for:
- [x] check_results.php (#147)
  - [x] Add "All" option (#155) and link directly to it
- [x] check_regional_record_markers.php
- [x] check_rounds.php (#154)

We should also take care of
- [x] #156

**Comment by SAuroux** [comment]
Just to clarify, this should only happen within a competition result posting process, where we work on a specific competitionid anyways.
