### ISSUE TITLE
Asynchronous job support

### ISSUE THREAD

**Issue by jfly** [cubing/worldcubeassociation.org#633]
After a discussion on the software@ mailing list, I think [delayed_job](https://github.com/collectiveidea/delayed_job) is the best implementation of Active Job for us. It's simple (we won't have to set up something new like redis) and persists the jobs, so we'll be able to keep track of what has and hasn't been done, even there are crashes.

- [x] This will be useful for potentially bursty jobs (like @jonatanklosko's recently merged #75)
- [x] One downside of delayed_job (and all the Active Job implementations I looked at) is that they don't concern themselves with storing metadata about past jobs. The solution seems to be to keep track of that data ourselves, see: http://stackoverflow.com/questions/7431920/delayed-jobs-save-completed-jobs/28217770#28217770.
- [x] https://www.sitepoint.com/delayed-jobs-best-practices/ might be useful reading when setting up delayed_job.
- [x] Create one worker per queue... we don't want emails to wait for admin scripts to run, for instance.
- [x] Notify `admin@` when jobs fail.
- [ ] #641 ~~https://github.com/ejschmitt/delayed_job_web?~~
- [ ] #165 ~~We also need some way to schedule jobs to run periodically. [clockwork](https://github.com/tomykaira/clockwork) might be a good addition to delayed_job for scheduling repeating work (such as #571 and eventually, some of our admin scripts).~~
- [ ] #642 ~~Convert all calls to `.deliver_now` to `deliver_later`?~~
  - [ ] ~~What about devise? See https://github.com/plataformatec/devise#activejob-integration~~
